/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.petshop;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static java.util.Date.from;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andy
 */
public class Login extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String hakakses;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    private void login() {
        try {

            String password;
            String nm;
//            String hakses;
     
            password = new String(txt_password.getPassword());
//            hakses = new String(cbb_status.getSelectedItem().toString());
            Statement st = con.createStatement();
            String sql = "select status from karyawan where username ='" + txt_user.getText() + "' and password ='" + password +"'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                hakakses = rs.getString(5);
            }
            if (hakakses.equals("")||hakakses.equals("Select Status")) {
                JOptionPane.showMessageDialog(this, "Masukan User dan Password", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Silahkan Masuk");
                menuLogin();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Periksa Nama dan Password Anda !", "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    private void menuLogin() {
        menu_admin mp = new menu_admin();
        Transaksi KM = new Transaksi();
        if (hakakses.equals(hakakses)) {
            JOptionPane.showMessageDialog(null, "Anda Masuk Sebagai "+ hakakses);
            mp.setVisible(true);
            this.dispose();
        } else if (hakakses.equals("Karyawan")) {
            JOptionPane.showMessageDialog(null, "Anda Masuk Sebagai " + hakakses);
            KM.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_dasar = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbb_status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_dasar.setBackground(new java.awt.Color(243, 156, 18));
        menu_dasar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu_dasar.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_user_45px.png"))); // NOI18N
        menu_dasar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_lock_40px_1.png"))); // NOI18N
        jLabel2.setToolTipText("");
        menu_dasar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        cbb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Admin", "Karyawan" }));
        menu_dasar.add(cbb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, 30));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menu_dasar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 80, 30));

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menu_dasar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 80, 30));

        jLabel5.setFont(new java.awt.Font("Remachine Script Personal Use", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_cat_75px.png"))); // NOI18N
        jLabel5.setText("ORION PETSHOP");
        menu_dasar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Data Control", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOGIN");
        menu_dasar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_close_window_35px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        menu_dasar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 5, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_minimize_window_35px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        menu_dasar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 50));
        menu_dasar.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menu_dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menu_dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(466, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname = txt_user.getText();
                char[] pswd = txt_password.getPassword();
                String password = new String(pswd);
                String status = cbb_status.getSelectedItem().toString();
                menu_admin mp = new menu_admin();
                if (uname.equals("") || password.equals("") || status.equals("Select")) {
                    JOptionPane.showMessageDialog(rootPane, "ada yang belum terisi!!");
                } else {
                    try {
                        con = Koneksi.getConnection();
                        pst = con.prepareStatement("select * from karyawan where username=? and password=?");
                        pst.setString(1, uname);
                        pst.setString(2, password);
                        rs = pst.executeQuery();
        
                        if (rs.next()) {
                            String s1 = rs.getString("status");
                           
                            if (status.equalsIgnoreCase("Admin") && s1.equalsIgnoreCase("Admin")) {
        
                                //                     mp.id_karyawan().setText(rs.getString("username"));
                                mp.setVisible(true);
                                this.dispose();
                            }
                        
                            else if (status.equalsIgnoreCase("Karyawan") && s1.equalsIgnoreCase("Karyawan")) {
                                Transaksi KM = new Transaksi();
                                KM.setVisible(true);
                                setVisible(false);
                            }
                            else{
                               JOptionPane.showMessageDialog(this, "Hak Akses Anda Berbeda "); 
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Username Atau Password salah");
                        }
        
                    } catch (Exception ex) {
                        System.out.println("" + ex);
                    }
                }

//        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel menu_dasar;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
