/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.petshop;

import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy
 */
public class menu_admin extends javax.swing.JFrame {

    DefaultTableModel model;
    Statement stt;
    ResultSet rss;

    /**
     * Creates new form menu_admin
     */
    public menu_admin() {
        initComponents();
        tabel_paket();
        tabel_karyawan();
        refresh_karywan();
        tabel_paket_penitipan();
        refresh_paket_penitipan();
        refresh_paket_grooming();
        auto_number_paket_penitipan();
        auto_number_karyawan();
        auto_number_paket_grooming();
        tabel_kandang();
        refresh_kandang();
        auto_number_kandang();
        flaset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckground = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        btn_panel_logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_adduser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_panel_datapaket = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_panel_kandang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_panel_home1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        panel_data_paket = new javax.swing.JPanel();
        panel_penitipan = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panel_groomin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        panel_kandang = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_no_kandang = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cbb_statuskandang = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_deskripsi_kandang = new javax.swing.JTextArea();
        btn_simpan_kandang = new javax.swing.JButton();
        btn_batal_kandang = new javax.swing.JButton();
        btn_hapus_kandang = new javax.swing.JButton();
        btn_edit_kandang = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_kandang = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel96 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        panel_adduser = new javax.swing.JPanel();
        txtidkar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtpas = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbbstatus = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtnotelpon = new javax.swing.JTextField();
        btntambahkaryawan = new javax.swing.JButton();
        btneditkaryawan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnhapuskaryawan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel94 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        form_grooming = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtidpaketgrooming = new javax.swing.JTextField();
        txtnamapaketgrooming = new javax.swing.JTextField();
        txt_keterangangroominf = new javax.swing.JTextField();
        txt_hargagrooming = new javax.swing.JTextField();
        btn_tambah_datagrooming = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_paket = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        btneditgrooming = new javax.swing.JButton();
        hapusgrooming = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        btn_batal_grooming = new javax.swing.JButton();
        jLabel98 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        form_penitipan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtidpaketpenitipan = new javax.swing.JTextField();
        txtnamapaketpenitipan = new javax.swing.JTextField();
        txt_keteranganpenitipan = new javax.swing.JTextField();
        txt_hargapenitpan = new javax.swing.JTextField();
        btn_simpan1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_paketpenitipan = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        btn_hapuspenitipan = new javax.swing.JButton();
        btneditpenitipan = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        btn_batal_penitipan = new javax.swing.JButton();
        jLabel99 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bckground.setBackground(new java.awt.Color(28, 37, 41));
        bckground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_panel.setBackground(new java.awt.Color(243, 156, 18));
        side_panel.setPreferredSize(new java.awt.Dimension(260, 500));
        side_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_panel_logout.setBackground(new java.awt.Color(243, 156, 18));
        btn_panel_logout.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_panel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_panel_logoutMousePressed(evt);
            }
        });
        btn_panel_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Data Control", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        btn_panel_logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_logout_rounded_left_30px_3.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        btn_panel_logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        side_panel.add(btn_panel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, -1));

        btn_adduser.setBackground(new java.awt.Color(243, 156, 18));
        btn_adduser.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adduserMousePressed(evt);
            }
        });
        btn_adduser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Data Control", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH USER");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        btn_adduser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_add_user_male_30px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        btn_adduser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 11, -1, -1));

        side_panel.add(btn_adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, -1));

        btn_panel_datapaket.setBackground(new java.awt.Color(243, 156, 18));
        btn_panel_datapaket.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_panel_datapaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_panel_datapaketMousePressed(evt);
            }
        });
        btn_panel_datapaket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Data Control", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Paket");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        btn_panel_datapaket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_file_submodule_30px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        btn_panel_datapaket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, -1, -1));

        side_panel.add(btn_panel_datapaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, -1));

        btn_panel_kandang.setBackground(new java.awt.Color(243, 156, 18));
        btn_panel_kandang.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_panel_kandang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_panel_kandangMousePressed(evt);
            }
        });
        btn_panel_kandang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Data Control", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kandang");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        btn_panel_kandang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_cat_cage_33px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        btn_panel_kandang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, -1));

        side_panel.add(btn_panel_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_cat_75px.png"))); // NOI18N
        side_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 80));

        jLabel18.setFont(new java.awt.Font("Remachine Script Personal Use", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ORION PETSHOP");
        side_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, -1));

        btn_panel_home1.setBackground(new java.awt.Color(255, 153, 51));
        btn_panel_home1.setPreferredSize(new java.awt.Dimension(120, 50));
        btn_panel_home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_panel_home1MousePressed(evt);
            }
        });
        btn_panel_home1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Data Control", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        btn_panel_home1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 11, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_home_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        btn_panel_home1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        side_panel.add(btn_panel_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, -1));

        bckground.add(side_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        panel_home.setBackground(new java.awt.Color(28, 37, 41));
        panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("FOrm Home");
        panel_home.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panel_home.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 10));

        bckground.add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 840, 590));

        panel_data_paket.setBackground(new java.awt.Color(28, 37, 41));
        panel_data_paket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_penitipan.setBackground(new java.awt.Color(44, 62, 80));
        panel_penitipan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_penitipanMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_house_125px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Boingo", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Paket Penitipan");

        javax.swing.GroupLayout panel_penitipanLayout = new javax.swing.GroupLayout(panel_penitipan);
        panel_penitipan.setLayout(panel_penitipanLayout);
        panel_penitipanLayout.setHorizontalGroup(
            panel_penitipanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penitipanLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel25)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_penitipanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(76, 76, 76))
        );
        panel_penitipanLayout.setVerticalGroup(
            panel_penitipanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penitipanLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(46, 46, 46))
        );

        panel_data_paket.add(panel_penitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 280, 250));

        panel_groomin.setBackground(new java.awt.Color(44, 62, 80));
        panel_groomin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_groominMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_cat_125px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Boingo", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Paket Grooming");

        javax.swing.GroupLayout panel_groominLayout = new javax.swing.GroupLayout(panel_groomin);
        panel_groomin.setLayout(panel_groominLayout);
        panel_groominLayout.setHorizontalGroup(
            panel_groominLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_groominLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_groominLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(36, 36, 36))
        );
        panel_groominLayout.setVerticalGroup(
            panel_groominLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_groominLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(48, 48, 48))
        );

        panel_data_paket.add(panel_groomin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 280, 250));

        jLabel97.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("FOrm Data paket");
        panel_data_paket.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panel_data_paket.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 10));

        bckground.add(panel_data_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 840, 590));

        panel_kandang.setBackground(new java.awt.Color(28, 37, 41));
        panel_kandang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Nomor Kandang");
        panel_kandang.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        panel_kandang.add(txt_no_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));

        jLabel35.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Status Kandang");
        panel_kandang.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cbb_statuskandang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Tersedia", "Terpakai" }));
        panel_kandang.add(cbb_statuskandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel36.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Deskripsi Kandang");
        panel_kandang.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txt_deskripsi_kandang.setColumns(20);
        txt_deskripsi_kandang.setRows(5);
        jScrollPane4.setViewportView(txt_deskripsi_kandang);

        panel_kandang.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, -1));

        btn_simpan_kandang.setText("Simpan");
        btn_simpan_kandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_kandangActionPerformed(evt);
            }
        });
        panel_kandang.add(btn_simpan_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        btn_batal_kandang.setText("Batal");
        btn_batal_kandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_kandangActionPerformed(evt);
            }
        });
        panel_kandang.add(btn_batal_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        btn_hapus_kandang.setText("Hapus");
        btn_hapus_kandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_kandangActionPerformed(evt);
            }
        });
        panel_kandang.add(btn_hapus_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        btn_edit_kandang.setText("Edit");
        btn_edit_kandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_kandangActionPerformed(evt);
            }
        });
        panel_kandang.add(btn_edit_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        tbl_kandang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kandang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kandangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_kandang);

        panel_kandang.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 380));

        jLabel96.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("FOrm Kandang");
        panel_kandang.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panel_kandang.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 10));

        bckground.add(panel_kandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 840, 580));

        panel_adduser.setBackground(new java.awt.Color(28, 37, 41));
        panel_adduser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_adduser.add(txtidkar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        jLabel14.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID Karyawan");
        panel_adduser.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama");
        panel_adduser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        panel_adduser.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));

        jLabel15.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Username");
        panel_adduser.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        panel_adduser.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, -1));

        jLabel16.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        panel_adduser.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        panel_adduser.add(txtpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, -1));

        jLabel21.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Status");
        panel_adduser.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        cbbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Karyawan" }));
        panel_adduser.add(cbbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 140, -1));

        jLabel22.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Alamat");
        panel_adduser.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        panel_adduser.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, -1));

        jLabel23.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nomor Telpon");
        panel_adduser.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        panel_adduser.add(txtnotelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 140, -1));

        btntambahkaryawan.setText("Tambah");
        btntambahkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahkaryawanActionPerformed(evt);
            }
        });
        panel_adduser.add(btntambahkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        btneditkaryawan.setText("Edit");
        btneditkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditkaryawanActionPerformed(evt);
            }
        });
        panel_adduser.add(btneditkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 70, -1));

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        panel_adduser.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 60, -1));

        btnhapuskaryawan.setText("Hapus");
        btnhapuskaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapuskaryawanActionPerformed(evt);
            }
        });
        panel_adduser.add(btnhapuskaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_userMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        panel_adduser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 510, -1));

        jLabel94.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("FOrm ADD user");
        panel_adduser.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panel_adduser.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 10));

        bckground.add(panel_adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 840, 590));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_minimize_window_35px_1.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        bckground.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, -5, -1, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_close_window_35px_1.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        bckground.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 40, 40));

        form_grooming.setBackground(new java.awt.Color(28, 37, 41));
        form_grooming.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Id Paket");
        form_grooming.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel27.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nama Paket");
        form_grooming.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Keterangan Paket");
        form_grooming.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel29.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Harga Paket");
        form_grooming.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        form_grooming.add(txtidpaketgrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 134, 27));
        form_grooming.add(txtnamapaketgrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 135, 27));
        form_grooming.add(txt_keterangangroominf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 215, 64));
        form_grooming.add(txt_hargagrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 135, 28));

        btn_tambah_datagrooming.setText("Simpan");
        btn_tambah_datagrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_datagroomingActionPerformed(evt);
            }
        });
        form_grooming.add(btn_tambah_datagrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        tbl_paket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_paket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_paketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_paket);

        form_grooming.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 410, 310));

        btneditgrooming.setText("Edit");
        btneditgrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditgroomingActionPerformed(evt);
            }
        });
        form_grooming.add(btneditgrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        hapusgrooming.setText("Hapus");
        hapusgrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusgroomingActionPerformed(evt);
            }
        });
        form_grooming.add(hapusgrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_go_back_50px_1.png"))); // NOI18N
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        form_grooming.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_batal_grooming.setText("Batal");
        btn_batal_grooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_groomingActionPerformed(evt);
            }
        });
        form_grooming.add(btn_batal_grooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel98.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("FOrm paket grooming");
        form_grooming.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        form_grooming.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 730, 10));

        bckground.add(form_grooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 840, 580));

        form_penitipan.setBackground(new java.awt.Color(28, 37, 41));
        form_penitipan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Id Paket");
        form_penitipan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel31.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nama Paket");
        form_penitipan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel32.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Keterangan Paket");
        form_penitipan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel33.setFont(new java.awt.Font("Data Control", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Harga Paket");
        form_penitipan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        form_penitipan.add(txtidpaketpenitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 134, 27));
        form_penitipan.add(txtnamapaketpenitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 135, 27));
        form_penitipan.add(txt_keteranganpenitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 215, 64));
        form_penitipan.add(txt_hargapenitpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 135, 28));

        btn_simpan1.setText("Tambah");
        btn_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan1ActionPerformed(evt);
            }
        });
        form_penitipan.add(btn_simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        tbl_paketpenitipan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_paketpenitipan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_paketpenitipanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_paketpenitipan);

        form_penitipan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 370, 300));

        btn_hapuspenitipan.setText("Hapus");
        btn_hapuspenitipan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapuspenitipanActionPerformed(evt);
            }
        });
        form_penitipan.add(btn_hapuspenitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        btneditpenitipan.setText("Edit");
        btneditpenitipan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditpenitipanActionPerformed(evt);
            }
        });
        form_penitipan.add(btneditpenitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 66, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_go_back_50px_1.png"))); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        form_penitipan.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_batal_penitipan.setText("Batal");
        btn_batal_penitipan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_penitipanActionPerformed(evt);
            }
        });
        form_penitipan.add(btn_batal_penitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel99.setFont(new java.awt.Font("Data Control", 0, 36)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("FOrm paket penitipan");
        form_penitipan.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        form_penitipan.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 730, 10));

        bckground.add(form_penitipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 840, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1116, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       private void flaset() {
        panel_adduser.setVisible(false);
        panel_groomin.setVisible(false);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }
//Kandang

    private void tabel_kandang() {
        model = new DefaultTableModel();
        tbl_kandang.setModel(model);
        model.addColumn("Nomor Kandang");
        model.addColumn("Status Kandang");
        model.addColumn("Deskripsi");

        tampil_tabel_kandang();
    }

    private void tampil_tabel_kandang() {

        Connection con = Koneksi.getConnection();
        try {
            stt = con.createStatement();
            String sql = " SELECT * FROM kandang";
            rss = stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o;
                o = new Object[3];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);

                model.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void auto_number_kandang() {
        try {
            Connection con = Koneksi.getConnection();
            Statement stat = con.createStatement();
            String sql = "SELECT MAX(right(nomor_kandang,1)) AS no FROM kandang";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txt_no_kandang.setText("KD0");
                } else {
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int n = 0; n < 3 - id_next; n++) {
                        no = "0" + no;
                    }
                    txt_no_kandang.setText("KD" + no);
                }

            }
        } catch (Exception e) {
        }
    }

    private void refresh_kandang() {

        txt_deskripsi_kandang.setText(null);
        cbb_statuskandang.setSelectedIndex(0);

    }

    //karyawan
    private void refresh_karywan() {

        txtalamat.setText(null);
        txtnama.setText(null);
        txtnotelpon.setText(null);
        txtpas.setText(null);
        txtuser.setText(null);
        cbbstatus.setSelectedIndex(0);

    }

    private void auto_number_karyawan() {
        try {
            Connection con = Koneksi.getConnection();
            Statement stat = con.createStatement();
            String sql = "SELECT MAX(right(id_karyawan,1)) AS no FROM karyawan";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txtidkar.setText("KY00");
                } else {
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int n = 0; n < 3 - id_next; n++) {
                        no = "0" + no;
                    }
                    txtidkar.setText("KY" + no);
                }

            }
        } catch (Exception e) {
        }
    }

    private void tampil_tabel_karyawan() {
        Connection con = Koneksi.getConnection();
        try {
            stt = con.createStatement();
            String sql = "SELECT * FROM karyawan";
            rss = stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o;
                o = new Object[7];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);
                o[3] = rss.getString(4);
                o[4] = rss.getString(5);
                o[5] = rss.getString(6);
                o[6] = rss.getString(7);

                model.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tabel_karyawan() {
        model = new DefaultTableModel();
        tbl_user.setModel(model);
        model.addColumn("ID Karyawan");
        model.addColumn("Nama");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Status");
        model.addColumn("Alamat");
        model.addColumn("Nomor Telpon");
        tampil_tabel_karyawan();
    }
    //warna

    void setcolor(JPanel panel) {
        panel.setBackground(new Color(255, 153, 51));
    }

    void resetcolor(JPanel panel) {
        panel.setBackground(new Color(243, 156, 18));
    }
    private void btn_adduserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adduserMousePressed
        setcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        panel_adduser.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_btn_adduserMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        setcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        panel_adduser.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        setcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        panel_adduser.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel2MousePressed

    private void btn_panel_datapaketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panel_datapaketMousePressed
        setcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(true);
        panel_kandang.setVisible(false);
        panel_adduser.setVisible(false);
        panel_home.setVisible(false);
        panel_groomin.setVisible(true);
        panel_penitipan.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
        refresh_grooming();

    }//GEN-LAST:event_btn_panel_datapaketMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        setcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(true);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        panel_groomin.setVisible(true);
        panel_penitipan.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
        refresh_grooming();
        panel_adduser.setVisible(false);

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        setcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(true);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        panel_groomin.setVisible(true);
        panel_penitipan.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
        refresh_grooming();
        panel_adduser.setVisible(false);

    }//GEN-LAST:event_jLabel4MousePressed

    private void btn_panel_kandangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panel_kandangMousePressed
        // TODO add your handling code here:
        setcolor(btn_panel_kandang);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(true);
        panel_adduser.setVisible(false);
        panel_home.setVisible(false);
        panel_groomin.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_btn_panel_kandangMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        setcolor(btn_panel_kandang);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(true);
        panel_adduser.setVisible(false);
        panel_home.setVisible(false);
        panel_groomin.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        setcolor(btn_panel_kandang);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_logout);
        resetcolor(btn_panel_home1);
        panel_adduser.setVisible(false);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(true);
        panel_home.setVisible(false);
        panel_groomin.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel6MousePressed

    private void btn_panel_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panel_logoutMousePressed
        setcolor(btn_panel_logout);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        int jawab = 0;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin melakukan Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            Login lgn = new Login();
            lgn.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btn_panel_logoutMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        setcolor(btn_panel_logout);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        int jawab = 0;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin melakukan Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            Login lgn = new Login();
            lgn.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        setcolor(btn_panel_logout);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_home1);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_home.setVisible(false);
        int jawab = 0;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin melakukan Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            Login lgn = new Login();
            lgn.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        int jawab = 0;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void btntambahkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahkaryawanActionPerformed
        // TODO add your handling code here:
        if (txtidkar.getText().equals("") || txtnama.getText().equals("") || txtuser.getText().equals(evt)
                || cbbstatus.getSelectedItem().equals("") || txtalamat.getText().equals("") || txtnotelpon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = ("INSERT INTO karyawan VALUES ('" + txtidkar.getText() + "','"
                        + txtnama.getText() + "','"
                        + txtuser.getText() + "','"
                        + txtpas.getText() + "','"
                        + cbbstatus.getSelectedItem().toString() + "','"
                        + txtalamat.getText() + "','"
                        + txtnotelpon.getText() + "')");

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_karyawan();
                tabel_karyawan();
                refresh_karywan();
                JOptionPane.showMessageDialog(null, "Penyimpanan Data User Berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }

    }//GEN-LAST:event_btntambahkaryawanActionPerformed

    private void btneditkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditkaryawanActionPerformed
        // TODO add your handling code here:
        if (txtidkar.getText().equals("") || txtnama.getText().equals("") || txtuser.getText().equals(evt)
                || cbbstatus.getSelectedItem().equals("") || txtalamat.getText().equals("") || txtnotelpon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = "UPDATE karyawan SET nama = '" + txtnama.getText() + "', username = '" + txtuser.getText()
                        + "', password = '" + txtpas.getText() + "',status= '"
                        + cbbstatus.getSelectedItem() + "',alamat= '" + txtalamat.getText() + "',no_telpon='" + txtnotelpon.getText() + "' WHERE id_karyawan = '" + txtidkar.getText() + "'";

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_karyawan();
                tabel_karyawan();
                refresh_karywan();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btneditkaryawanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        refresh_karywan();
        auto_number_karyawan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapuskaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapuskaryawanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from karyawan where id_karyawan='" + txtidkar.getText() + "'";
            java.sql.Connection con = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement psts = con.prepareStatement(sql);
            psts.execute();
            auto_number_karyawan();
            tabel_karyawan();

            refresh_karywan();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnhapuskaryawanActionPerformed

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
        auto_number_karyawan();
        int baris = tbl_user.rowAtPoint(evt.getPoint());
        String id_karyawan = tbl_user.getValueAt(baris, 0).toString();
        txtidkar.setText(id_karyawan);
        String nama = tbl_user.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        String username = tbl_user.getValueAt(baris, 2).toString();
        txtuser.setText(username);
        String password = tbl_user.getValueAt(baris, 3).toString();
        txtpas.setText(password);
        String status = tbl_user.getValueAt(baris, 4).toString();
        cbbstatus.setSelectedItem(status);
        String alamat = tbl_user.getValueAt(baris, 5).toString();
        txtalamat.setText(alamat);
        String telp = tbl_user.getValueAt(baris, 6).toString();
        txtnotelpon.setText(telp);

    }//GEN-LAST:event_tbl_userMouseClicked

    private void tbl_userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseReleased
        // TODO add your handling code here:
        //           if (evt.isPopupTrigger()){
        //            JTable source = (JTable)evt.getSource();
        //            int row = source.rowAtPoint( evt.getPoint() );
        //            int column = source.columnAtPoint( evt.getPoint() );
        //
        //            if (! source.isRowSelected(row))
        //                source.changeSelection(row, column, false, false);
        //
        //            jpop.show(evt.getComponent(), evt.getX(), evt.getY());
        //        }
    }//GEN-LAST:event_tbl_userMouseReleased

    private void panel_penitipanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_penitipanMouseClicked
        // TODO add your handling code here:
        panel_groomin.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(true);
        panel_data_paket.setVisible(false);
        panel_adduser.setVisible(false);
        refresh_penitipan();
    }//GEN-LAST:event_panel_penitipanMouseClicked

    private void panel_groominMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_groominMouseClicked
        // TODO add your handling code here:
        panel_groomin.setVisible(false);
        panel_penitipan.setVisible(false);
        form_grooming.setVisible(true);
        form_penitipan.setVisible(false);
        panel_data_paket.setVisible(false);
        panel_adduser.setVisible(false);
        refresh_grooming();


    }//GEN-LAST:event_panel_groominMouseClicked
//Grooming

    private void tabel_paket() {
        model = new DefaultTableModel();
        tbl_paket.setModel(model);
        model.addColumn("Kode Paket");
        model.addColumn("Nama Paket");
        model.addColumn("Keterangan");
        model.addColumn("Harga ");
        tampil_tabel_paket();
    }

    private void tampil_tabel_paket() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Connection con = Koneksi.getConnection();
        try {
            stt = con.createStatement();
            String sql = " SELECT * FROM data_paket WHERE kode_paket LIKE 'GR%'";
            rss = stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o;
                o = new Object[4];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);
                o[3] = rss.getString(4);

                model.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void auto_number_paket_grooming() {
        try {
            Connection con = Koneksi.getConnection();
            Statement stat = con.createStatement();
            String sql = "SELECT MAX(right(kode_paket,1)) AS no FROM data_paket";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txtidpaketgrooming.setText("GR00");
                } else {
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int n = 0; n < 3 - id_next; n++) {
                        no = "0" + no;
                    }
                    txtidpaketgrooming.setText("GR" + no);
                }

            }
        } catch (Exception e) {
        }
    }

    private void refresh_paket_grooming() {

        txtnamapaketgrooming.setText(null);
        txt_keterangangroominf.setText(null);
        txt_hargagrooming.setText(null);

    }
    private void btn_tambah_datagroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_datagroomingActionPerformed
        // TODO add your handling code here:
        if (txtidpaketgrooming.getText().equals("") || txtnamapaketgrooming.getText().equals("")
                || txt_keterangangroominf.getText().equals(evt) || txt_hargagrooming.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = ("INSERT INTO data_paket VALUES ('" + txtidpaketgrooming.getText() + "','"
                        + txtnamapaketgrooming.getText() + "','"
                        + txt_keterangangroominf.getText() + "','"
                        + txt_hargagrooming.getText() + "')");

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_paket_grooming();
                tabel_paket();
                tampil_tabel_paket();
                refresh_paket_grooming();
                JOptionPane.showMessageDialog(null, "Penyimpanan paket grooming berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btn_tambah_datagroomingActionPerformed

    private void tbl_paketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_paketMouseClicked
        // TODO add your handling code here:
        auto_number_paket_grooming();
        int baris = tbl_paket.rowAtPoint(evt.getPoint());
        String kode_paket = tbl_paket.getValueAt(baris, 0).toString();
        txtidpaketgrooming.setText(kode_paket);
        String nama_paket = tbl_paket.getValueAt(baris, 1).toString();
        txtnamapaketgrooming.setText(nama_paket);
        String keterangan_paket = tbl_paket.getValueAt(baris, 2).toString();
        txt_keterangangroominf.setText(keterangan_paket);
        String harga = tbl_paket.getValueAt(baris, 3).toString();
        txt_hargagrooming.setText(harga);
    }//GEN-LAST:event_tbl_paketMouseClicked

    private void btneditgroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditgroomingActionPerformed
        // TODO add your handling code here:
        if (txtidpaketgrooming.getText().equals("") || txtnamapaketgrooming.getText().equals("")
                || txt_keterangangroominf.getText().equals(evt) || txt_hargagrooming.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = "UPDATE data_paket SET nama_paket = '" + txtnamapaketgrooming.getText() + "', keterangan_paket = '" + txt_keterangangroominf.getText()
                        + "', harga_paket = '" + txt_hargagrooming.getText() + "' WHERE kode_paket = '" + txtidpaketgrooming.getText() + "'";

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_paket_grooming();
                tabel_paket();
                refresh_paket_grooming();
                JOptionPane.showMessageDialog(null, "Edit paket grooming berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btneditgroomingActionPerformed

    private void hapusgroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusgroomingActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from data_paket where kode_paket='" + txtidpaketgrooming.getText() + "'";
            java.sql.Connection con = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement psts = con.prepareStatement(sql);
            psts.execute();

            auto_number_paket_grooming();
            tabel_paket();
            refresh_paket_grooming();
            JOptionPane.showMessageDialog(this, "Hapus paket grooming berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
    }//GEN-LAST:event_hapusgroomingActionPerformed
//penitipan

    private void tabel_paket_penitipan() {
        model = new DefaultTableModel();
        tbl_paketpenitipan.setModel(model);
        model.addColumn("Kode Paket");
        model.addColumn("Nama Paket");
        model.addColumn("Keterangan");
        model.addColumn("Harga ");
        tampil_tabel_paket_penitipan();
    }

    private void tampil_tabel_paket_penitipan() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Connection con = Koneksi.getConnection();
        try {
            stt = con.createStatement();
            String sql = " SELECT * FROM data_paket WHERE kode_paket LIKE 'PN%'";
            rss = stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o;
                o = new Object[4];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);
                o[3] = rss.getString(4);

                model.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void auto_number_paket_penitipan() {
        try {
            Connection con = Koneksi.getConnection();
            Statement stat = con.createStatement();
            String sql = "SELECT MAX(right(kode_paket,1)) AS no FROM data_paket";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txtidpaketpenitipan.setText("PN00");
                } else {
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int n = 0; n < 3 - id_next; n++) {
                        no = "0" + no;
                    }
                    txtidpaketpenitipan.setText("PN" + no);
                }

            }
        } catch (Exception e) {
        }
    }

    private void refresh_paket_penitipan() {

        txtnamapaketpenitipan.setText(null);
        txt_keteranganpenitipan.setText(null);
        txt_hargapenitpan.setText(null);

    }
    private void btn_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan1ActionPerformed
        if (txtidpaketpenitipan.getText().equals("") || txtnamapaketpenitipan.getText().equals("")
                || txt_keteranganpenitipan.getText().equals(evt) || txt_hargapenitpan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = ("INSERT INTO data_paket VALUES ('" + txtidpaketpenitipan.getText() + "','"
                        + txtnamapaketpenitipan.getText() + "','"
                        + txt_keteranganpenitipan.getText() + "','"
                        + txt_hargapenitpan.getText() + "')");

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_paket_penitipan();
                tabel_paket_penitipan();
                tampil_tabel_paket_penitipan();
                refresh_paket_penitipan();
                JOptionPane.showMessageDialog(null, "Penyimpanan paket penitipan berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btn_simpan1ActionPerformed

    private void tbl_paketpenitipanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_paketpenitipanMouseClicked
        // TODO add your handling code here:
        auto_number_paket_grooming();
        int barispenitipan = tbl_paketpenitipan.rowAtPoint(evt.getPoint());
        String kode_paket = tbl_paketpenitipan.getValueAt(barispenitipan, 0).toString();
        txtidpaketpenitipan.setText(kode_paket);
        String nama_paket = tbl_paketpenitipan.getValueAt(barispenitipan, 1).toString();
        txtnamapaketpenitipan.setText(nama_paket);
        String keterangan_paket = tbl_paketpenitipan.getValueAt(barispenitipan, 2).toString();
        txt_keteranganpenitipan.setText(keterangan_paket);
        String harga = tbl_paketpenitipan.getValueAt(barispenitipan, 3).toString();
        txt_hargapenitpan.setText(harga);
    }//GEN-LAST:event_tbl_paketpenitipanMouseClicked

    private void btn_hapuspenitipanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapuspenitipanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from data_paket where kode_paket='" + txtidpaketpenitipan.getText() + "'";
            java.sql.Connection con = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement psts = con.prepareStatement(sql);
            psts.execute();
            auto_number_paket_penitipan();
            tabel_paket_penitipan();
            refresh_paket_penitipan();
            JOptionPane.showMessageDialog(null, "Hapus paket penitipan berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
    }//GEN-LAST:event_btn_hapuspenitipanActionPerformed

    private void btneditpenitipanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditpenitipanActionPerformed
        // TODO add your handling code here:
        if (txtidpaketpenitipan.getText().equals("") || txtnamapaketpenitipan.getText().equals("")
                || txt_keteranganpenitipan.getText().equals(evt) || txt_hargapenitpan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = "UPDATE data_paket SET nama_paket = '" + txtnamapaketpenitipan.getText() + "', keterangan_paket = '" + txt_keteranganpenitipan.getText()
                        + "', harga_paket = '" + txt_hargapenitpan.getText() + "' WHERE kode_paket = '" + txtidpaketpenitipan.getText() + "'";

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_paket_penitipan();
                tabel_paket_penitipan();
                refresh_paket_penitipan();
                JOptionPane.showMessageDialog(null, "Edit paket penitipan berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btneditpenitipanActionPerformed

    private void btn_simpan_kandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_kandangActionPerformed
        // TODO add your handling code here:
        if (txt_no_kandang.getText().equals("") || cbb_statuskandang.getSelectedItem().equals("") || txt_deskripsi_kandang.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String sql = ("INSERT INTO kandang VALUES ('" + txt_no_kandang.getText() + "','"
                        + cbb_statuskandang.getSelectedItem().toString() + "','"
                        + txt_deskripsi_kandang.getText() + "')");

                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_kandang();
                tabel_kandang();

                refresh_kandang();
                JOptionPane.showMessageDialog(null, "Penyimpanan data kandang berhasil");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btn_simpan_kandangActionPerformed

    private void btn_hapus_kandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_kandangActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from kandang where nomor_kandang='" + txt_no_kandang.getText() + "'";
            java.sql.Connection con = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement psts = con.prepareStatement(sql);
            psts.execute();

            auto_number_kandang();
            tabel_kandang();

            refresh_kandang();
            JOptionPane.showMessageDialog(null, "Hapus data kandang berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
    }//GEN-LAST:event_btn_hapus_kandangActionPerformed

    private void btn_edit_kandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_kandangActionPerformed
        // TODO add your handling code here:
        if (txt_no_kandang.getText().equals("") || cbb_statuskandang.getSelectedItem().equals("") || txt_deskripsi_kandang.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukan data !", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "UPDATE kandang SET status_kandang = '" + cbb_statuskandang.getSelectedItem()
                        + "', deskripsi_kandang = '" + txt_deskripsi_kandang.getText()
                        + "' WHERE nomor_kandang = '" + txt_no_kandang.getText() + "'";
                java.sql.Connection con = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement psts = con.prepareStatement(sql);
                psts.execute();

                auto_number_kandang();
                tabel_kandang();

                refresh_kandang();
                JOptionPane.showMessageDialog(null, "Edit data kandang");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_btn_edit_kandangActionPerformed

    private void tbl_kandangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kandangMouseClicked
        // TODO add your handling code here:

        auto_number_kandang();
        int baris_kandang = tbl_kandang.rowAtPoint(evt.getPoint());
        String no_kandang = tbl_kandang.getValueAt(baris_kandang, 0).toString();
        txt_no_kandang.setText(no_kandang);
        String status = tbl_kandang.getValueAt(baris_kandang, 1).toString();
        cbb_statuskandang.setSelectedItem(status);
        String deskripsi_kandang = tbl_kandang.getValueAt(baris_kandang, 2).toString();
        txt_deskripsi_kandang.setText(deskripsi_kandang);

    }//GEN-LAST:event_tbl_kandangMouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        setcolor(btn_panel_home1);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_adduser.setVisible(false);
        panel_home.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        setcolor(btn_panel_home1);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_adduser.setVisible(false);
        panel_home.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_jLabel11MousePressed

    private void btn_panel_home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panel_home1MousePressed
        setcolor(btn_panel_home1);
        resetcolor(btn_panel_datapaket);
        resetcolor(btn_adduser);
        resetcolor(btn_panel_kandang);
        resetcolor(btn_panel_logout);
        panel_data_paket.setVisible(false);
        panel_kandang.setVisible(false);
        panel_adduser.setVisible(false);
        panel_home.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
    }//GEN-LAST:event_btn_panel_home1MousePressed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        panel_data_paket.setVisible(true);
        panel_penitipan.setVisible(true);
        panel_groomin.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
        refresh_grooming();
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        panel_data_paket.setVisible(true);
        panel_penitipan.setVisible(true);
        panel_groomin.setVisible(true);
        form_grooming.setVisible(false);
        form_penitipan.setVisible(false);
        refresh_penitipan();
    }//GEN-LAST:event_jLabel38MouseClicked
    private void refresh_grooming() {
        txtnamapaketgrooming.setText("");
        txt_keterangangroominf.setText("");
        txt_hargagrooming.setText("");
    }
    private void btn_batal_groomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_groomingActionPerformed
        refresh_grooming();
        auto_number_paket_grooming();
    }//GEN-LAST:event_btn_batal_groomingActionPerformed
    private void refresh_penitipan() {
        txtnamapaketpenitipan.setText("");
        txt_keteranganpenitipan.setText("");
        txt_hargapenitpan.setText("");
    }
    private void btn_batal_penitipanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_penitipanActionPerformed
        refresh_penitipan();
        auto_number_paket_penitipan();
    }//GEN-LAST:event_btn_batal_penitipanActionPerformed
    private void refresh_kandang_admin() {
        cbb_statuskandang.setSelectedIndex(0);
        txt_deskripsi_kandang.setText("");
    }
    private void btn_batal_kandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_kandangActionPerformed
        refresh_kandang_admin();
        auto_number_kandang();
    }//GEN-LAST:event_btn_batal_kandangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bckground;
    private javax.swing.JPanel btn_adduser;
    private javax.swing.JButton btn_batal_grooming;
    private javax.swing.JButton btn_batal_kandang;
    private javax.swing.JButton btn_batal_penitipan;
    private javax.swing.JButton btn_edit_kandang;
    private javax.swing.JButton btn_hapus_kandang;
    private javax.swing.JButton btn_hapuspenitipan;
    private javax.swing.JPanel btn_panel_datapaket;
    private javax.swing.JPanel btn_panel_home1;
    private javax.swing.JPanel btn_panel_kandang;
    private javax.swing.JPanel btn_panel_logout;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JButton btn_simpan_kandang;
    private javax.swing.JButton btn_tambah_datagrooming;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btneditgrooming;
    private javax.swing.JButton btneditkaryawan;
    private javax.swing.JButton btneditpenitipan;
    private javax.swing.JButton btnhapuskaryawan;
    private javax.swing.JButton btntambahkaryawan;
    private javax.swing.JComboBox<String> cbb_statuskandang;
    private javax.swing.JComboBox<String> cbbstatus;
    private javax.swing.JPanel form_grooming;
    private javax.swing.JPanel form_penitipan;
    private javax.swing.JButton hapusgrooming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panel_adduser;
    private javax.swing.JPanel panel_data_paket;
    private javax.swing.JPanel panel_groomin;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_kandang;
    private javax.swing.JPanel panel_penitipan;
    private javax.swing.JPanel side_panel;
    private javax.swing.JTable tbl_kandang;
    private javax.swing.JTable tbl_paket;
    private javax.swing.JTable tbl_paketpenitipan;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextArea txt_deskripsi_kandang;
    private javax.swing.JTextField txt_hargagrooming;
    private javax.swing.JTextField txt_hargapenitpan;
    private javax.swing.JTextField txt_keterangangroominf;
    private javax.swing.JTextField txt_keteranganpenitipan;
    private javax.swing.JTextField txt_no_kandang;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidkar;
    private javax.swing.JTextField txtidpaketgrooming;
    private javax.swing.JTextField txtidpaketpenitipan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamapaketgrooming;
    private javax.swing.JTextField txtnamapaketpenitipan;
    private javax.swing.JTextField txtnotelpon;
    private javax.swing.JTextField txtpas;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
